name: {{project_name.snakeCase()}}
description: {{description}}
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  mason_logger: ^0.1.1
  pub_updater: ^0.2.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1

executables:
  {{executable_name.snakeCase()}}: